In [2]:
import geopandas as gpd
import folium
#import shapely
#import googlemaps
import pandas as pd
import pdb
from scrape_stores import scrape_stores_URL

In [4]:
#testing scraping function
URL = "https://www.starbucks.com/store-locator?map=38.898935,-77.026836,15z"

store_df = scrape_stores_URL(URL, [])
store_df.head()

,storeNumber,city,countrySubdivisionCode,countryCode,addressLines,hours,latitude,longitude
0,23466-230290,Washington,DC,US,1000 H Street NW,4:30 AM to 7:00 PM,38.89964,-77.02678
1,70004-26515,Washington,DC,US,775 12th St. NW,6:00 AM to 5:00 PM,38.89912,-77.02774
2,7784-66360,Washington,DC,US,"555 11th Street, NW",5:00 AM to 7:00 PM,38.89662,-77.02680
3,10725-100383,Washington,DC,US,901 New York Avenue NW,4:30 AM to 7:00 PM,38.90181,-77.02559
4,7569-238095,Washington,DC,US,1304 F Street NW,5:30 AM to 6:00 PM,38.89717,-77.03029

In [ ]:
#Building a grid of points to exhaustively sample within a city
#lat, long steps at zoom = 15 ~ 2/3 as wide as area shown
long_step = 0.03
lat_step = 0.01